jobs:
  - deploy-site:
      serial-group: << pipeline.project.slug >>/deploy-site
      context:
        - bot-context
        - slack-secrets
        - sst
        - github
      filters:
        branches:
          only:
            - main
