jobs:
  - release:
      serial-group: << pipeline.project.slug >>/release/<< pipeline.parameters.package >>
      context:
        - turbo-cache
        - bot-context
        - slack-secrets
      filters:
        tags:
          only:
            - /^@agent-facets\/.+@\d+\..+/
        branches:
          ignore:
            - /.*/
