jobs:
  - release:
      context:
        - turbo-cache
        - bot-context
        - slack-secrets
      filters:
        tags:
          only:
            - /^@agent-facets\/.+@\d+\..+/
            - /^agent-facets@\d+\..+/
        branches:
          ignore:
            - /.*/
      post-steps:
        - notify-failure
        - notify-success
