jobs:
  - check:
      context: slack-secrets
      filters:
        branches:
          only:
            - release
      post-steps:
        - notify-failure
  - release:
      requires:
        - check
      context:
        - release
        - slack-secrets
      filters:
        branches:
          only:
            - release
      post-steps:
        - notify-failure
        - notify-success
