docker:
  - image: cimg/base:current
resource_class: medium
steps:
  - setup-mise
  - run:
      name: Disable CLI build cache
      command: cp packages/cli/turbo.ci.json packages/cli/turbo.json
  - run-check
  - run:
      name: Restore CLI turbo config
      command: git checkout packages/cli/turbo.json
  - store_test_results:
      path: test-results

