docker:
  - image: cimg/base:current
resource_class: medium
environment:
  LEFTHOOK: "0"
steps:
  - setup-env
  - run-check
  - store_test_results:
      path: test-results
  - run:
      name: Version Changesets
      command: bun scripts/release/version.ts
  - run:
      name: Tag Release
      command: bun scripts/release/tag.ts
  - notify-failure
