/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AgentFacetsLanding": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "AgentFacetsSite": {
      "type": "sst.aws.Router"
      "url": string
    }
    "InstallScript": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}

import "sst"
export {}