jobs:
  - check:
      context:
        - turbo-cache
        - github
      filters:
        branches:
          ignore:
            - main
  - main-pipeline:
      serial-group: << pipeline.project.slug >>/main-pipeline
      context:
        - turbo-cache
        - bot-context
        - slack-secrets
        - github
      filters:
        branches:
          only:
            - main
