import { afterEach, beforeEach, describe, expect, mock, spyOn, test } from 'bun:test'
import dedent from 'dedent'
import * as ci from '../lib/ci'
import { io } from '../lib/io'
import { SAMPLE_CHANGELOG, shellResult, silenceIO } from '../lib/test-helpers'

describe('version.ts', () => {
  beforeEach(() => {
    silenceIO()
  })

  afterEach(() => {
    mock.restore()
  })

  describe('buildChangesets', () => {
    function setupVersionPath() {
      spyOn(io.shell, 'mintGitHubAppToken').mockResolvedValue('fake-gh-token')
      spyOn(io.gh, 'authSetupGit').mockResolvedValue(shellResult())
      spyOn(io.shell, 'changesetVersion').mockResolvedValue(shellResult())
      spyOn(io.shell, 'bunInstall').mockResolvedValue(shellResult())
      spyOn(io.git, 'diff').mockResolvedValue(shellResult('', 1))
      spyOn(io.git, 'diffCached').mockResolvedValue(shellResult('', 0))
      spyOn(io.git, 'config').mockResolvedValue(shellResult())
      spyOn(io.git, 'checkout').mockResolvedValue(shellResult())
      spyOn(io.git, 'add').mockResolvedValue(shellResult())
      spyOn(io.git, 'commit').mockResolvedValue(shellResult())
      spyOn(io.git, 'push').mockResolvedValue(shellResult())
      spyOn(io.shell, 'readFile').mockResolvedValue(SAMPLE_CHANGELOG)
      spyOn(io.shell, 'writeFile').mockResolvedValue(0)
    }

    test('creates a new PR with rich body when changesets are pending', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md', 'README.md'])
      setupVersionPath()

      const loadSpy = spyOn(ci, 'loadWorkspacePackages')
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' }])
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.1.0', dir: 'packages/core' }])

      spyOn(io.gh, 'prList').mockResolvedValue('')
      const prCreateSpy = spyOn(io.gh, 'prCreate').mockResolvedValue(shellResult())

      const { buildChangesets } = await import('./version')
      const code = await buildChangesets()

      expect(code).toBe(0)
      expect(loadSpy).toHaveBeenCalledTimes(2)
      expect(prCreateSpy).toHaveBeenCalledTimes(1)

      const body = prCreateSpy.mock.calls[0]?.[3] as string
      expect(body).toBe(
        `${dedent`
        This PR was auto-generated by the release workflow. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

        # Releases
        ## @agent-facets/core@1.1.0

        ### Minor Changes

        - Added a cool new feature
      `}\n`,
      )
    })

    test('updates existing PR body instead of creating a new one', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md'])
      setupVersionPath()

      spyOn(ci, 'loadWorkspacePackages')
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' }])
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.1.0', dir: 'packages/core' }])

      spyOn(io.gh, 'prList').mockResolvedValue('42\n')
      const prCreateSpy = spyOn(io.gh, 'prCreate').mockResolvedValue(shellResult())
      const prUpdateSpy = spyOn(io.gh, 'prUpdate').mockResolvedValue(shellResult())

      const { buildChangesets } = await import('./version')
      const code = await buildChangesets()

      expect(code).toBe(0)
      expect(prCreateSpy).not.toHaveBeenCalled()
      expect(prUpdateSpy).toHaveBeenCalledTimes(1)

      const body = prUpdateSpy.mock.calls[0]?.[2] as string
      expect(body).toBe(
        `${dedent`
        This PR was auto-generated by the release workflow. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

        # Releases
        ## @agent-facets/core@1.1.0

        ### Minor Changes

        - Added a cool new feature
      `}\n`,
      )
    })

    test('exits early when changeset version produces no diff', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md'])
      spyOn(io.shell, 'mintGitHubAppToken').mockResolvedValue('fake-gh-token')
      spyOn(ci, 'loadWorkspacePackages').mockResolvedValue([
        { name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' },
      ])
      spyOn(io.shell, 'changesetVersion').mockResolvedValue(shellResult())
      spyOn(io.shell, 'bunInstall').mockResolvedValue(shellResult())

      spyOn(io.git, 'diff').mockResolvedValue(shellResult('', 0))
      spyOn(io.git, 'diffCached').mockResolvedValue(shellResult('', 0))

      const gitCheckoutSpy = spyOn(io.git, 'checkout').mockResolvedValue(shellResult())

      const { buildChangesets } = await import('./version')
      const code = await buildChangesets()

      expect(code).toBe(0)
      expect(gitCheckoutSpy).not.toHaveBeenCalled()
    })

    test('sets both GH_TOKEN and GITHUB_TOKEN', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md'])
      setupVersionPath()

      spyOn(ci, 'loadWorkspacePackages')
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' }])
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.1.0', dir: 'packages/core' }])

      spyOn(io.gh, 'prList').mockResolvedValue('')
      spyOn(io.gh, 'prCreate').mockResolvedValue(shellResult())

      const { buildChangesets } = await import('./version')
      await buildChangesets()

      expect(process.env.GH_TOKEN).toBe('fake-gh-token')
      expect(process.env.GITHUB_TOKEN).toBe('fake-gh-token')
    })

    test('creates PR targeting main branch', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md'])
      setupVersionPath()

      spyOn(ci, 'loadWorkspacePackages')
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' }])
        .mockResolvedValueOnce([{ name: '@agent-facets/core', version: '1.1.0', dir: 'packages/core' }])

      spyOn(io.gh, 'prList').mockResolvedValue('')
      const prCreateSpy = spyOn(io.gh, 'prCreate').mockResolvedValue(shellResult())

      const { buildChangesets } = await import('./version')
      await buildChangesets()

      expect(prCreateSpy.mock.calls[0]?.[0]).toBe('main')
    })
  })

  describe('no pending changesets', () => {
    test('exits 0 when no changesets are pending', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['README.md'])

      const { buildChangesets } = await import('./version')
      const code = await buildChangesets()

      expect(code).toBe(0)
    })
  })

  describe('error handling', () => {
    test('returns 1 when changeset version fails', async () => {
      spyOn(io.shell, 'scanDir').mockResolvedValue(['funny-turtle.md'])
      spyOn(io.shell, 'mintGitHubAppToken').mockResolvedValue('fake-gh-token')
      spyOn(ci, 'loadWorkspacePackages').mockResolvedValue([
        { name: '@agent-facets/core', version: '1.0.0', dir: 'packages/core' },
      ])
      spyOn(io.shell, 'changesetVersion').mockRejectedValue(new Error('changeset version failed'))

      const { buildChangesets } = await import('./version')
      const code = await buildChangesets().catch(() => 1)

      expect(code).toBe(1)
    })
  })
})
