jobs:
  - check:
      context:
        - turbo-cache
        - slack-secrets
      post-steps:
        - notify-failure
  - changesets:
      requires:
        - check
      context:
        - release
        - slack-secrets
      filters:
        branches:
          only:
            - main
      post-steps:
        - notify-failure
  - tag-release:
      requires:
        - check
      context:
        - release
        - slack-secrets
      filters:
        branches:
          only:
            - main
      post-steps:
        - notify-failure
