import { getChangelogEntry } from '@changesets/release-utils'

export interface WorkspacePackage {
  name: string
  version?: string
  dir: string
  private?: boolean
}

/**
 * Given a list of filenames from the .changeset directory,
 * returns only the ones that are actual changesets (not README.md).
 */
export function filterPendingChangesets(files: string[]): string[] {
  return files.filter((f) => f.endsWith('.md') && f !== 'README.md')
}

/**
 * Determine whether we should publish (no pending changesets)
 * or create a version PR (pending changesets exist).
 */
export function shouldPublish(pendingChangesets: string[]): boolean {
  return pendingChangesets.length === 0
}

/**
 * Check whether any workspace package has a local version
 * that doesn't yet exist on the npm registry.
 *
 * Packages without a `version` field in `package.json` are excluded —
 * they are workspace-only helpers (e.g. `@agent-facets/common`) whose
 * release is suppressed upstream by the changesets `ignore` list in
 * `.changeset/config.json`. This defensive filter prevents `npmViewFn`
 * from being called with a versionless package (which would return
 * `null`, mismatch `undefined`, and perpetually report as "unpublished",
 * causing tag.ts to keep firing every main-pipeline run).
 */
export async function hasUnpublishedVersions(
  packages: WorkspacePackage[],
  npmViewFn: (pkg: string) => Promise<string | null>,
): Promise<boolean> {
  for (const pkg of packages) {
    if (!pkg.version) continue
    const npmVersion = await npmViewFn(pkg.name)
    if (npmVersion !== pkg.version) return true
  }

  return false
}

// ---------------------------------------------------------------------------
// Version PR body generation
// ---------------------------------------------------------------------------

/** Max characters for a GitHub PR body (GitHub limit is 65536, we use 60K for safety) */
const MAX_CHARACTERS = 60_000

/**
 * Explicit package display order — most important first.
 * Packages not listed here sort after listed ones, by bump level.
 */
const PACKAGE_ORDER: Record<string, number> = {
  'agent-facets': 0,
  '@agent-facets/protocol': 1,
  '@agent-facets/brand': 2,
}

/** Compare two package names by their defined display order. */
export function comparePackageOrder(nameA: string, nameB: string): number {
  const orderA = PACKAGE_ORDER[nameA] ?? Number.MAX_SAFE_INTEGER
  const orderB = PACKAGE_ORDER[nameB] ?? Number.MAX_SAFE_INTEGER
  return orderA - orderB
}

/** A per-package transformed entry for CHANGELOG rewrite */
export interface TransformedEntry {
  dir: string
  version: string
  content: string
}

/** Return value of buildVersionPrBody — PR body + per-package entries for CHANGELOG rewrite */
export interface VersionPrResult {
  body: string
  entries: TransformedEntry[]
}

/**
 * Build a rich PR body for the Version Packages PR.
 *
 * Reads each changed package's CHANGELOG.md, extracts the entry for its
 * new version using the changesets library parser, transforms the content
 * (groups changes by contributor, cleans spacing), and composes a body
 * with a `# Releases` section and per-package subsections.
 *
 * Also returns per-package transformed entries so callers can rewrite
 * CHANGELOG.md files on disk with the same clean format.
 */
export async function buildVersionPrBody(
  changedPackages: { name: string; version: string; dir: string }[],
  readFile: (path: string) => Promise<string>,
): Promise<VersionPrResult> {
  const packageInfos = await Promise.all(
    changedPackages.map(async (pkg) => {
      const changelog = await readFile(`${pkg.dir}/CHANGELOG.md`)
      const entry = getChangelogEntry(changelog, pkg.version)
      const transformed = transformChangelogContent(entry.content)
      return {
        name: pkg.name,
        dir: pkg.dir,
        version: pkg.version,
        header: `## ${pkg.name}@${pkg.version}`,
        content: transformed,
        highestLevel: entry.highestLevel,
      }
    }),
  )

  const sorted = packageInfos.sort((a, b) => {
    const order = comparePackageOrder(a.name, b.name)
    if (order !== 0) return order
    // Fall back to bump level (higher = more important = first)
    return b.highestLevel - a.highestLevel
  })

  const messageHeader =
    'This PR was auto-generated by the release workflow. ' +
    "When you're ready to do a release, you can merge this and the packages will be published to npm automatically. " +
    "If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.\n"

  const releasesHeading = '# Releases'

  let body = [messageHeader, releasesHeading, ...sorted.map((info) => `${info.header}\n\n${info.content}`)].join('\n')

  // Truncation safety — same as official changesets/action
  if (body.length > MAX_CHARACTERS) {
    body = [
      messageHeader,
      releasesHeading,
      '\n> The changelog information of each package has been omitted from this message, as the content exceeds the size limit.\n',
      ...sorted.map((info) => `${info.header}\n\n`),
    ].join('\n')
  }

  if (body.length > MAX_CHARACTERS) {
    body = [
      messageHeader,
      releasesHeading,
      '\n> All release information have been omitted from this message, as the content exceeds the size limit.',
    ].join('\n')
  }

  const entries = sorted.map((info) => ({ dir: info.dir, version: info.version, content: info.content }))

  return { body, entries }
}

// ---------------------------------------------------------------------------
// Changelog content transformation
// ---------------------------------------------------------------------------
/** Matches a changelog line with GitHub attribution from @changesets/changelog-github */
const ATTRIBUTED_LINE_RE = /^-\s+\[`([a-f0-9]+)`]\(([^)]+)\)\s+Thanks\s+\[@([^\]]+)]\(([^)]+)\)\s*!\s*-\s*(.+)$/

/** Matches "Updated dependencies [hash]" lines */
const UPDATED_DEPS_RE = /^-\s+Updated dependencies/

interface AttributedChange {
  hash: string
  username: string
  userUrl: string
  description: string
}

interface UserGroup {
  username: string
  userUrl: string
  changes: AttributedChange[]
  firstSeen: number
}

/**
 * Transform a changelog entry's content: group changes by contributor,
 * sort by volume, clean up spacing, and separate dependency updates.
 *
 * Input is the raw content from `getChangelogEntry().content` which has been
 * through remarkStringify (extra indentation, loose list spacing).
 */
export function transformChangelogContent(content: string): string {
  // Split into sections by ### headings (e.g., ### Patch Changes, ### Minor Changes)
  const sections = splitSections(content)
  const transformed = sections.map(transformSection)
  return transformed.join('\n')
}

interface Section {
  heading: string
  lines: string[]
}

function splitSections(content: string): Section[] {
  const sections: Section[] = []
  let currentHeading = ''
  let currentLines: string[] = []

  for (const line of content.split('\n')) {
    if (line.startsWith('### ')) {
      if (currentHeading || currentLines.length > 0) {
        sections.push({ heading: currentHeading, lines: currentLines })
      }
      currentHeading = line
      currentLines = []
    } else {
      currentLines.push(line)
    }
  }

  if (currentHeading || currentLines.length > 0) {
    sections.push({ heading: currentHeading, lines: currentLines })
  }

  return sections
}

function transformSection(section: Section): string {
  // Parse list items from the section lines.
  // Items can be multi-line (continuation lines are indented).
  const items = parseListItems(section.lines)

  const attributed: AttributedChange[] = []
  const singleLineUnattributed: string[] = []
  const depItems: string[] = []

  for (const item of items) {
    // Normalize remark's `-   ` (3 spaces) back to `- ` (1 space)
    const normalized = item.replace(/^-\s{2,}/, '- ')

    const match = normalized.match(ATTRIBUTED_LINE_RE)
    if (match?.[1] && match[3] && match[4] && match[5]) {
      attributed.push({
        hash: match[1],
        username: match[3],
        userUrl: match[4],
        description: match[5],
      })
    } else if (UPDATED_DEPS_RE.test(normalized)) {
      depItems.push(normalized)
    } else if (normalized.trim()) {
      singleLineUnattributed.push(normalized)
    }
  }

  // Group attributed changes by user
  const groupMap = new Map<string, UserGroup>()
  for (const [i, change] of attributed.entries()) {
    const existing = groupMap.get(change.username)
    if (existing) {
      existing.changes.push(change)
    } else {
      groupMap.set(change.username, {
        username: change.username,
        userUrl: change.userUrl,
        changes: [change],
        firstSeen: i,
      })
    }
  }

  const groups = [...groupMap.values()]
  // Sort: most changes first, ties preserve first-seen order
  groups.sort((a, b) => b.changes.length - a.changes.length || a.firstSeen - b.firstSeen)

  // Separate multi-change groups from single-change users
  const multiGroups = groups.filter((g) => g.changes.length > 1)
  const singleGroups = groups.filter((g) => g.changes.length === 1)

  const output: string[] = []

  // Add section heading
  if (section.heading) {
    output.push(section.heading)
    output.push('')
  }

  // Multi-change groups
  for (const group of multiGroups) {
    output.push(`**@${group.username}** — Thanks! (${group.changes.length} changes)`)
    for (const change of group.changes) {
      output.push(`- ${change.hash} ${change.description}`)
    }
    output.push('')
  }

  // Individual contributions (single-change users + unattributed)
  const hasMultiGroups = multiGroups.length > 0
  const individualItems = [
    ...singleGroups.map((g) => {
      const c = g.changes[0] as AttributedChange
      return `- ${c.hash} Thanks @${c.username}! - ${c.description}`
    }),
    ...singleLineUnattributed,
  ]

  if (individualItems.length > 0 && hasMultiGroups) {
    output.push('#### Individual Contributions')
    for (const item of individualItems) {
      output.push(item)
    }
    output.push('')
  } else if (individualItems.length > 0) {
    // No multi-groups, just list them directly
    for (const item of individualItems) {
      output.push(item)
    }
    output.push('')
  }

  // Updated dependencies
  if (depItems.length > 0) {
    output.push('#### Updated Dependencies')
    // Collect dep items — collapse "Updated dependencies [hash]" lines
    // and extract the actual dependency bumps from continuation lines
    const depBumps = extractDependencyBumps(depItems)
    for (const bump of depBumps) {
      output.push(bump)
    }
    output.push('')
  }

  // Remove trailing blank lines
  while (output.length > 0 && output[output.length - 1] === '') {
    output.pop()
  }

  return `${output.join('\n')}\n`
}

/**
 * Parse raw section lines into individual list items.
 * A list item starts with `-` at column 0; continuation lines are indented.
 */
function parseListItems(lines: string[]): string[] {
  const items: string[] = []
  let current = ''

  for (const line of lines) {
    const trimmed = line.trimStart()
    if (trimmed.startsWith('- ') && !line.startsWith(' ') && !line.startsWith('\t')) {
      if (current) items.push(current)
      current = trimmed
    } else if (current && trimmed) {
      // Continuation line — append but for our purposes we flatten
      // Multi-line items like "Updated dependencies" have indented sub-items
      current += `\n${line}`
    } else if (!trimmed && current) {
      // Blank line between loose list items — don't break the item,
      // just skip (we'll handle spacing in output)
    }
  }

  if (current) items.push(current)
  return items
}

/**
 * Extract dependency bump lines from "Updated dependencies" items.
 * Input items look like:
 *   "- Updated dependencies [hash]\n  - @pkg@version"
 * or sometimes multiple "Updated dependencies" lines followed by indented deps.
 * We extract just the `- @pkg@version` lines with the hash prefixed.
 */
function extractDependencyBumps(items: string[]): string[] {
  const bumps: string[] = []

  for (const item of items) {
    const lines = item.split('\n')
    // First line: "- Updated dependencies [hash]"
    const firstLine = lines[0] ?? ''
    const headerMatch = firstLine.match(/Updated dependencies\s*\[([a-f0-9]+)\]/)
    const hash = headerMatch?.[1]

    // Sub-lines: indented dependency entries like "  - @agent-facets/protocol@0.1.2"
    for (let i = 1; i < lines.length; i++) {
      const depLine = lines[i] ?? ''
      const depMatch = depLine.match(/^\s+-\s+(.+)/)
      if (depMatch?.[1]) {
        bumps.push(hash ? `- ${hash} ${depMatch[1]}` : `- ${depMatch[1]}`)
      }
    }

    // If no sub-lines, the deps might be in the next item
    // (loose list from remark splits them). Just record the header hash.
    if (lines.length === 1 && hash) {
      // Will be paired with a subsequent dep item — skip for now
    }
  }

  return bumps
}

// ---------------------------------------------------------------------------
// CHANGELOG rewrite
// ---------------------------------------------------------------------------

/**
 * Replace a specific version's entry in a full CHANGELOG.md string
 * with new transformed content.
 *
 * Finds `## <version>` and replaces everything up to the next `## ` heading
 * (or end of file) with the new content.
 */
export function replaceChangelogEntry(changelog: string, version: string, newContent: string): string {
  const lines = changelog.split('\n')
  const versionHeading = `## ${version}`

  let startIdx = -1
  let endIdx = lines.length

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? ''
    if (startIdx === -1) {
      // Look for the version heading
      if (line.trim() === versionHeading) {
        startIdx = i
      }
    } else {
      // Found the start — look for the next ## heading
      if (line.startsWith('## ') && i > startIdx) {
        endIdx = i
        break
      }
    }
  }

  if (startIdx === -1) return changelog // version not found, return unchanged

  const before = lines.slice(0, startIdx + 1) // includes the ## version line
  const after = lines.slice(endIdx)
  const trimmedContent = newContent.replace(/\n+$/, '')

  return [...before, '', trimmedContent, '', ...after].join('\n')
}

// ---------------------------------------------------------------------------
// Ignored-package guard
// ---------------------------------------------------------------------------

/** A single package bump declared in a changeset's front-matter. */
export interface PackageBump {
  name: string
  bump: string
}

/**
 * Parse the package bumps from a single changeset file's contents.
 *
 * Changeset front-matter looks like:
 *
 *   ---
 *   "@agent-facets/protocol": patch
 *   "agent-facets": minor
 *   ---
 *   Summary text...
 *
 * Returns one entry per quoted `"name": bump` line inside the leading
 * front-matter block. Package names without surrounding quotes, or content
 * outside the front-matter block, are ignored. The bump value is captured
 * verbatim (e.g. `patch`, `minor`, `major`) for diagnostic reporting; this
 * guard does not interpret it.
 */
export function parseChangesetBumps(content: string): PackageBump[] {
  const lines = content.split('\n')

  // Locate the front-matter block delimited by the first two `---` fences.
  let openIdx = -1
  let closeIdx = -1
  for (let i = 0; i < lines.length; i++) {
    if (lines[i]?.trim() === '---') {
      if (openIdx === -1) {
        openIdx = i
      } else {
        closeIdx = i
        break
      }
    }
  }

  if (openIdx === -1 || closeIdx === -1) return []

  const bumps: PackageBump[] = []
  const lineRe = /^\s*"([^"]+)"\s*:\s*(\S+)\s*$/
  for (let i = openIdx + 1; i < closeIdx; i++) {
    const match = (lines[i] ?? '').match(lineRe)
    if (match?.[1] && match[2]) {
      bumps.push({ name: match[1], bump: match[2] })
    }
  }

  return bumps
}

/** A pending changeset together with the bumps it declares. */
export interface ParsedChangeset {
  file: string
  bumps: PackageBump[]
}

/**
 * A forbidden bump found in a pending changeset.
 *
 * `reason` discriminates why the bump is illegal:
 * - `ignored`  — the package exists in the workspace but is listed in
 *   `.changeset/config.json` `ignore`; it is never released, and bumping it
 *   breaks the release/deploy pipeline.
 * - `unknown`  — the package is not a workspace package at all (a fake or
 *   misnamed entry, e.g. from a typo in the Changesets UI). Versioning it
 *   would fail outright.
 */
export interface ForbiddenBump {
  file: string
  name: string
  bump: string
  reason: 'ignored' | 'unknown'
}

/**
 * Result of scanning pending changesets for forbidden package bumps.
 *
 * `ok: false` carries the structured violations so a caller (e.g. a test)
 * can render a clear failure without parsing a message string. Failure here
 * is part of the contract — a guard that finds a forbidden bump — not an
 * exceptional condition, so it is modeled as data rather than a thrown error.
 */
export type ForbiddenBumpScanResult = { ok: true } | { ok: false; violations: ForbiddenBump[] }

/**
 * Scan parsed pending changesets for any bump that targets a package which
 * either (a) is listed in the changesets `ignore` array, or (b) is not a
 * known workspace package at all. Pure: callers supply the already-parsed
 * changesets, the ignore list (from `.changeset/config.json`), and the set
 * of valid workspace package names (from `loadWorkspacePackages()`).
 *
 * `ignore` takes precedence over `knownPackages`: an ignored package is a
 * real workspace package, so it is classified as `ignored`, not `unknown`.
 */
export function findForbiddenBumps(
  changesets: ParsedChangeset[],
  ignore: string[],
  knownPackages: string[],
): ForbiddenBumpScanResult {
  const ignored = new Set(ignore)
  const known = new Set(knownPackages)
  const violations: ForbiddenBump[] = []

  for (const changeset of changesets) {
    for (const { name, bump } of changeset.bumps) {
      if (ignored.has(name)) {
        violations.push({ file: changeset.file, name, bump, reason: 'ignored' })
      } else if (!known.has(name)) {
        violations.push({ file: changeset.file, name, bump, reason: 'unknown' })
      }
    }
  }

  return violations.length === 0 ? { ok: true } : { ok: false, violations }
}

/**
 * Render a forbidden-bump scan failure as a human-readable, multi-line
 * message for surfacing in CI / test output. Groups violations by reason so
 * the operator sees the two distinct failure classes separately.
 */
export function formatForbiddenBumps(violations: ForbiddenBump[]): string {
  const sections: string[] = []

  const ignored = violations.filter((v) => v.reason === 'ignored')
  if (ignored.length > 0) {
    sections.push(
      'Changeset(s) bump packages listed in `.changeset/config.json` `ignore`. ' +
        'These packages are never released and bumping them breaks the release/deploy pipeline. ' +
        'Remove the offending package(s) from the changeset(s):',
      ...ignored.map((v) => `  - ${v.file}: "${v.name}": ${v.bump}`),
    )
  }

  const unknown = violations.filter((v) => v.reason === 'unknown')
  if (unknown.length > 0) {
    if (sections.length > 0) sections.push('')
    sections.push(
      'Changeset(s) bump packages that are not in the workspace (fake or misnamed). ' +
        'Fix the package name(s) in the changeset(s):',
      ...unknown.map((v) => `  - ${v.file}: "${v.name}": ${v.bump}`),
    )
  }

  return sections.join('\n')
}
