import { getChangelogEntry, sortChangelogEntries } from '@changesets/release-utils'

export interface WorkspacePackage {
  name: string
  version: string
  dir: string
  private?: boolean
}

/**
 * Given a list of filenames from the .changeset directory,
 * returns only the ones that are actual changesets (not README.md).
 */
export function filterPendingChangesets(files: string[]): string[] {
  return files.filter((f) => f.endsWith('.md') && f !== 'README.md')
}

/**
 * Determine whether we should publish (no pending changesets)
 * or create a version PR (pending changesets exist).
 */
export function shouldPublish(pendingChangesets: string[]): boolean {
  return pendingChangesets.length === 0
}

/**
 * Check whether any non-private workspace package has a local version
 * that doesn't yet exist on the npm registry.
 */
export async function hasUnpublishedVersions(
  packages: WorkspacePackage[],
  npmViewFn: (pkg: string) => Promise<string | null>,
): Promise<boolean> {
  const publishable = packages.filter((p) => !p.private)

  for (const pkg of publishable) {
    const npmVersion = await npmViewFn(pkg.name)
    if (npmVersion !== pkg.version) return true
  }

  return false
}

// ---------------------------------------------------------------------------
// Version PR body generation
// ---------------------------------------------------------------------------

/** Max characters for a GitHub PR body (GitHub limit is 65536, we use 60K for safety) */
const MAX_CHARACTERS = 60_000

/**
 * Build a rich PR body for the Version Packages PR.
 *
 * Reads each changed package's CHANGELOG.md, extracts the entry for its
 * new version using the changesets library parser, and composes a body
 * with a `# Releases` section and per-package subsections.
 */
export async function buildVersionPrBody(
  changedPackages: { name: string; version: string; dir: string }[],
  readFile: (path: string) => Promise<string>,
): Promise<string> {
  const packageInfos = await Promise.all(
    changedPackages.map(async (pkg) => {
      const changelog = await readFile(`${pkg.dir}/CHANGELOG.md`)
      const entry = getChangelogEntry(changelog, pkg.version)
      return {
        header: `## ${pkg.name}@${pkg.version}`,
        content: entry.content,
        highestLevel: entry.highestLevel,
        private: false,
      }
    }),
  )

  const sorted = packageInfos.sort(sortChangelogEntries)

  const messageHeader =
    'This PR was auto-generated by the release workflow. ' +
    "When you're ready to do a release, you can merge this and the packages will be published to npm automatically. " +
    "If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.\n"

  const releasesHeading = '# Releases'

  let body = [messageHeader, releasesHeading, ...sorted.map((info) => `${info.header}\n\n${info.content}`)].join('\n')

  // Truncation safety — same as official changesets/action
  if (body.length > MAX_CHARACTERS) {
    body = [
      messageHeader,
      releasesHeading,
      '\n> The changelog information of each package has been omitted from this message, as the content exceeds the size limit.\n',
      ...sorted.map((info) => `${info.header}\n\n`),
    ].join('\n')
  }

  if (body.length > MAX_CHARACTERS) {
    body = [
      messageHeader,
      releasesHeading,
      '\n> All release information have been omitted from this message, as the content exceeds the size limit.',
    ].join('\n')
  }

  return body
}

// ---------------------------------------------------------------------------
// Publish output parsing
// ---------------------------------------------------------------------------

export interface PublishedPackage {
  name: string
  version: string
}

/**
 * Parse `changeset publish` stdout for `New tag:` lines.
 *
 * In a monorepo, each published package produces a line like:
 *   `New tag:  @scope/name@version`
 *
 * For a single-package repo:
 *   `New tag:  v<version>`
 */
export function parsePublishedPackages(stdout: string): PublishedPackage[] {
  const packages: PublishedPackage[] = []
  const regex = /New tag:\s+(@[^/]+\/[^@]+|[^/]+)@([^\s]+)/

  for (const line of stdout.split('\n')) {
    const match = line.match(regex)
    if (match?.[1] && match[2]) {
      packages.push({ name: match[1], version: match[2] })
    }
  }

  return packages
}
