import { describe, expect, test } from 'bun:test'
import {
  buildVersionPrBody,
  filterPendingChangesets,
  hasUnpublishedVersions,
  parsePublishedPackages,
  shouldPublish,
  type WorkspacePackage,
} from './changesets'

describe('filterPendingChangesets', () => {
  test('returns empty array when no files', () => {
    expect(filterPendingChangesets([])).toEqual([])
  })

  test('filters out README.md', () => {
    expect(filterPendingChangesets(['README.md'])).toEqual([])
  })

  test('returns only .md files that are not README.md', () => {
    const files = ['README.md', 'funny-turtle.md', 'brave-lion.md']
    expect(filterPendingChangesets(files)).toEqual(['funny-turtle.md', 'brave-lion.md'])
  })

  test('filters out non-.md files', () => {
    const files = ['funny-turtle.md', 'config.json', 'notes.txt']
    expect(filterPendingChangesets(files)).toEqual(['funny-turtle.md'])
  })

  test('handles mix of everything', () => {
    const files = ['README.md', 'funny-turtle.md', 'config.json', 'brave-lion.md', '.gitkeep']
    expect(filterPendingChangesets(files)).toEqual(['funny-turtle.md', 'brave-lion.md'])
  })
})

describe('shouldPublish', () => {
  test('returns true when no pending changesets', () => {
    expect(shouldPublish([])).toBe(true)
  })

  test('returns false when there are pending changesets', () => {
    expect(shouldPublish(['funny-turtle.md'])).toBe(false)
  })

  test('returns false when multiple pending changesets', () => {
    expect(shouldPublish(['funny-turtle.md', 'brave-lion.md'])).toBe(false)
  })
})

describe('hasUnpublishedVersions', () => {
  const mockNpm = (registry: Record<string, string>) => {
    return async (pkg: string): Promise<string | null> => registry[pkg] ?? null
  }

  test('returns false when all versions match npm', async () => {
    const packages: WorkspacePackage[] = [
      { name: '@agent-facets/core', version: '0.1.1', dir: 'packages/core' },
      { name: 'agent-facets', version: '0.1.1', dir: 'packages/cli' },
    ]
    const result = await hasUnpublishedVersions(
      packages,
      mockNpm({ '@agent-facets/core': '0.1.1', 'agent-facets': '0.1.1' }),
    )
    expect(result).toBe(false)
  })

  test('returns true when one version is ahead of npm', async () => {
    const packages: WorkspacePackage[] = [
      { name: '@agent-facets/core', version: '0.2.0', dir: 'packages/core' },
      { name: 'agent-facets', version: '0.1.1', dir: 'packages/cli' },
    ]
    const result = await hasUnpublishedVersions(
      packages,
      mockNpm({ '@agent-facets/core': '0.1.1', 'agent-facets': '0.1.1' }),
    )
    expect(result).toBe(true)
  })

  test('returns true when package is not on npm yet', async () => {
    const packages: WorkspacePackage[] = [{ name: '@agent-facets/brand', version: '0.1.0', dir: 'packages/brand' }]
    const result = await hasUnpublishedVersions(packages, mockNpm({}))
    expect(result).toBe(true)
  })

  test('skips private packages', async () => {
    const packages: WorkspacePackage[] = [
      { name: 'private-pkg', version: '1.0.0', dir: 'packages/private', private: true },
      { name: '@agent-facets/core', version: '0.1.1', dir: 'packages/core' },
    ]
    const result = await hasUnpublishedVersions(packages, mockNpm({ '@agent-facets/core': '0.1.1' }))
    expect(result).toBe(false)
  })

  test('returns false for empty package list', async () => {
    const result = await hasUnpublishedVersions([], mockNpm({}))
    expect(result).toBe(false)
  })
})

describe('buildVersionPrBody', () => {
  const sampleChangelog = `# @agent-facets/core

## 0.2.0

### Minor Changes

- Added a cool new feature

### Patch Changes

- Fixed a bug

## 0.1.0

### Minor Changes

- Initial release
`

  const mockReadFile = (files: Record<string, string>) => {
    return async (path: string): Promise<string> => {
      const content = files[path]
      if (!content) throw new Error(`File not found: ${path}`)
      return content
    }
  }

  test('generates PR body with release sections', async () => {
    const body = await buildVersionPrBody(
      [{ name: '@agent-facets/core', version: '0.2.0', dir: 'packages/core' }],
      mockReadFile({ 'packages/core/CHANGELOG.md': sampleChangelog }),
    )

    expect(body).toContain('# Releases')
    expect(body).toContain('## @agent-facets/core@0.2.0')
    expect(body).toContain('Added a cool new feature')
    expect(body).toContain('Fixed a bug')
    // Should not include content from older versions
    expect(body).not.toContain('Initial release')
  })

  test('includes header message', async () => {
    const body = await buildVersionPrBody(
      [{ name: '@agent-facets/core', version: '0.2.0', dir: 'packages/core' }],
      mockReadFile({ 'packages/core/CHANGELOG.md': sampleChangelog }),
    )

    expect(body).toContain('auto-generated by the release workflow')
    expect(body).toContain('packages will be published to npm automatically')
  })

  test('handles multiple packages', async () => {
    const cliChangelog = `# agent-facets

## 0.3.0

### Minor Changes

- New CLI command
`
    const body = await buildVersionPrBody(
      [
        { name: '@agent-facets/core', version: '0.2.0', dir: 'packages/core' },
        { name: 'agent-facets', version: '0.3.0', dir: 'packages/cli' },
      ],
      mockReadFile({
        'packages/core/CHANGELOG.md': sampleChangelog,
        'packages/cli/CHANGELOG.md': cliChangelog,
      }),
    )

    expect(body).toContain('## @agent-facets/core@0.2.0')
    expect(body).toContain('## agent-facets@0.3.0')
    expect(body).toContain('New CLI command')
  })

  test('truncates when body exceeds 60K characters', async () => {
    const longContent = 'x'.repeat(70_000)
    const hugeChangelog = `# pkg\n\n## 1.0.0\n\n### Patch Changes\n\n- ${longContent}\n`

    const body = await buildVersionPrBody(
      [{ name: 'huge-pkg', version: '1.0.0', dir: 'packages/huge' }],
      mockReadFile({ 'packages/huge/CHANGELOG.md': hugeChangelog }),
    )

    expect(body.length).toBeLessThanOrEqual(60_000)
    expect(body).toContain('omitted from this message')
  })
})

describe('parsePublishedPackages', () => {
  test('parses scoped package tags', () => {
    const stdout = `
info npm info @agent-facets/core
New tag:  @agent-facets/core@0.1.3
New tag:  agent-facets@0.1.4
info All packages published
`
    const result = parsePublishedPackages(stdout)
    expect(result).toEqual([
      { name: '@agent-facets/core', version: '0.1.3' },
      { name: 'agent-facets', version: '0.1.4' },
    ])
  })

  test('returns empty array when no tags found', () => {
    const stdout = 'Some random output\nNo packages to publish'
    expect(parsePublishedPackages(stdout)).toEqual([])
  })

  test('returns empty array for empty string', () => {
    expect(parsePublishedPackages('')).toEqual([])
  })

  test('handles single-package repo format', () => {
    const stdout = 'New tag:  v1.2.3'
    // The regex expects name@version, v1.2.3 doesn't match that pattern
    // In a single-package repo, the tag format is different
    expect(parsePublishedPackages(stdout)).toEqual([])
  })

  test('handles mixed output with noise', () => {
    const stdout = `
Running: npm publish --access public
@agent-facets/core@0.2.0
packages published successfully:
@agent-facets/core@0.2.0
Creating git tags...
New tag:  @agent-facets/core@0.2.0
`
    const result = parsePublishedPackages(stdout)
    expect(result).toEqual([{ name: '@agent-facets/core', version: '0.2.0' }])
  })
})
